# Use Node.js 14 as base image
FROM node:20-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY spicelab/ .
WORKDIR /app/spicelab

# Install dependencies
RUN npm install

# Copy rest of the application
# Build the Next.js application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
# CMD ["npm", "run", "dev"]
